### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by d7laungani** [ScorpionResponse/freelancefinder#1]
Sorry, for the dumb post but I am an IOS developer and am trying to find freelancer jobs. I found your post on HN and would like to use this software to help me find leads. How do I install and use your software.

Thanks!

**Comment by d7laungani** [comment]
Any help on this? Thank!

**Comment by ScorpionResponse** [comment]
It is still in beta really.  I plan on launching it in the next month or so.  If you want to try to run it yourself, you may install VirtualBox/Vagrant and run it as a vagrant box locally.

**Comment by d7laungani** [comment]
I hate to keep bugging you but I setup the freelancebox but I need the login username and password.

**Comment by ScorpionResponse** [comment]
If you deployed the code out of the git repo as is then the login is the same as in:
https://github.com/ScorpionResponse/freelancefinder/blob/master/ansible/group_vars/webservers#L26

specifically:
django_superuser_name: 'admin'
django_superuser_email: 'admin@example.com'
django_superuser_password: 'abc123abc'

To be completely honest, I am kind of surprised it worked that far.  So far I've only ever deployed it locally during development and so I haven't really bothered to get it working properly elsewhere.

**Comment by d7laungani** [comment]
I actually had some other issues and could not get it to run. Since you are going to deploy it so soon. I would love to beta test for you when you are closer to release. Thanks!

**Comment by ScorpionResponse** [comment]
Yes, I will let you know.  Thanks for your interest.

**Comment by ScorpionResponse** [comment]
I've put things together to get the site up and running.  It is at https://freelancefinder.work/ .  I'd love for you to sign up and tell me your thoughts.

**Comment by d7laungani** [comment]
Sorry, I didn't see this message earlier
